with open('src/App.jsx.orig2', 'r') as f:
    lines = f.readlines()

# The partner section is lines 579-618 (0-indexed) inclusive
# Replace with new dynamic partner section

new_partner_lines = [
    '                  📍 Nearby Channel Partners',
    '                </h3>',
    '',
    '                <p>',
    '                  Showing potential partners in:',
    '                  <strong>',
    '                    {" "}',
    '                    {formData.district},{" "}',
    '                    {formData.state}',
    '                  </strong>',
    '                </p>',
    '',
    '                {recommendedScheme &&',
    '                  formData.state &&',
    '                  findNearestEligiblePartner(',
    '                    recommendedScheme,',
    '                    stateCapitals[formData.state].lat,',
    '                    stateCapitals[formData.state].lng',
    '                  ) ? (',
    '                    <div>',
    '                      <p>',
    '                        Nearest eligible partner for{" "}',
    '                        <strong>',
    '                          {recommendedScheme.name}',
        '                        </strong>:',
                      '                      </p>',
                      '                      <div className="partner-card" style={{ borderLeft: "4px solid #10b981" }}>',
                      '',
        '                        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "8px" }}>',
                      '',
        '                          <span>',
        '            {findNearestEligiblePartner(',
        '              recommendedScheme,',
        '              stateCapitals[formData.state].lat,',
        '              stateCapitals[formData.state].lng',
        '            }.name)',
        '          </span>',
                      '',
        '                            <span style={{ fontSize: "0.75rem", color: "#64748b" }}>',
        '              {findNearestEligiblePartner(',
        '                recommendedScheme,',
        '                stateCapitals[formData.state].lat,',
        '                stateCapitals[formData.state].lng',
        '              }.distance)',
        '            </span>',
                      '',
                      '                          </div>',
                      '',
                      '                          <div>',
        '                            <span style={{ fontSize: "0.75rem", color: "#64748b" }}>Type: </span>',
        '                            <strong>',
        '                              {findNearestEligiblePartner(',
        '                                recommendedScheme,',
        '                                stateCapitals[formData.state].lat,',
        '                                stateCapitals[formData.state].lng',
        '                              }.type)',
        '                          </div>',
                      '',
                      '                          <div>',
        '                            <span style={{ fontSize: "0.75rem", color: "#64748b" }}>Fund Utilization: </span>',
        '                            <strong>',
        '                              {findNearestEligiblePartner(',
        '                                recommendedScheme,',
        '                                stateCapitals[formData.state].lat,',
        '                                stateCapitals[formData.state].lng',
        '                              }.fundUtilization%),',
        '                            </strong>',
                      '</div>',
                      '',
                      '                          <div>',
        '                            <span style={{ fontSize: "0.75rem", color: "#64748b" }}>NPA Status: </span>',
        '<strong style={{',
                          '                              color: findNearestEligiblePartner(',
        '                                recommendedScheme,',
        '                                stateCapitals[formData.state].lat,',
        '                                stateCapitals[formData.state].lng',
        '                              }.npaStatus === "NPA"',
        '                                ? "#dc2626"',
        '                                : "#10b981",',
        '                          }>',
                          '                              {findNearestEligiblePartner(',
        '                                recommendedScheme,',
        '                                stateCapitals[formData.state].lat,',
        '                                stateCapitals[formData.state].lng',
        '                              }.npaStatus)',
                        '</strong>',
                      '</div>',
                      '',
                      '                          <div>',
        '                            <span style={{ fontSize: "0.75rem", color: "#64748b" }}>Supported Schemes: </span>',
       '<strong>',
                          '                              {findNearestEligiblePartner(',
        '                                recommendedScheme,',
        '                                stateCapitals[formData.state].lat,',
        '                                stateCapitals[formData.state].lng',
        '                              }.supportedSchemes',
        '                                .map((s) => {',
        '                                  const schemeName = schemes.find(',
        '                                    (s) => s.id === s',
                                  ');',
                                  '                                  return schemeName',
                                    '                                    ? schemeName.shortName',
                                    '                                    : s;',
                                '                                )',
                                '                                .join(", ")}',
                            '</strong>',
                        '</div>',
                      '</div>',
                    ') : (',
                      '                      <p>',
        '                        No eligible channel partners found for this scheme.',
                        '                        {" "}',
                        '                        Select a state and district to locate nearby partners.',
                      '                      </p>',
                    ')',
                '',
                '          )',
                '        }',
                '',
            ]

    # Replace lines 579-618 (0-indexed) with the new lines
    # Old: lines[579:619] (since slice end is exclusive)
    # New: new_partner_lines
    
    # Verify the range
    print(f"Old lines 579-618 (0-indexed): {len(lines[579:619])} lines")
    print(f"New lines: {len(new_partner_lines)} lines")
    
    # Create new content
    new_content = lines[:579] + new_partner_lines + lines[619:]
    
    with open('src/App.jsx', 'w') as f:
        f.write('\n'.join(new_content))
    print("Partner section replaced successfully")